### Importing NumPy

```python
import numpy as np
```

### Array Creation Routines

```python
np.empty(shape, dtype, order)
np.empty_like(prototype, dtype, order)

np.zeros(shape, dtype, order)
np.zeros_like(a, dtype, order)

np.ones(shape, dtype, order)
np.ones_like(a, dtype, order)

np.full(shape, fill_value, dtype, order)
np.full_like(a, fill_value, dtype, order)

np.identity(n, dtype)
np.eye(N, M, k, dtype, order)

np.diag(v, k)
np.diagflat(v, k)

np.tri(N, M, k, dtype)
np.tril(m, k)
np.triu(m, k)

np.vander(x, N, increasing)

np.arange(start, stop, step, dtype)

np.linspace(start, stop, num, endpoint, dtype, retstep)
np.logspace(start, stop, num, endpoint, base, dtype)
np.geomspace(start, stop, num, endpoint, dtype)

np.meshgrid(*xi, copy, sparse, indexing)

np.loadtxt(fname, comments, skiprows, usecols, max_rows, delimiter, converters, dtype, ndim)

np.array(object, dtype, copy, order, ndim)

np.fromfunction(function, shape, dtype)
np.fromiter(iter, shape, count)
np.fromstring(string, dtype, count, sep)
```

### Random Sampling

```python
rng = np.random.default_rng(seed)

rng.integers(low, high, endpoint, size, dtype)
rng.random(size, dtype)

rng.uniform(low, high, size)
rng.normal(loc, scale, size)

rng.choice(a, size, shuffle, replace, p, axis)

rng.shuffle(x, axis)
rng.permutation(x, axis)
rng.permuted(x, axis, out)
```

### Logic Functions

```python
np.any(a, axis, out)
np.all(a, axis, out)

np.logical_and(x1, x2, out) # x1 & x2
np.logical_or(x1, x2, out) # x1 | x2
np.logical_not(x, out) # ~x
np.logical_xor(x1, x2, out) # x1 ^ x2

np.greater(x1, x2, out) # x1 > x2
np.greater_equal(x1, x2, out) # x1 >= x2

np.less(x1, x2, out) # x1 < x2
np.less_equal(x1, x2, out) # x1 <= x2

np.equal(x1, x2, out) # x1 == x2
np.not_equal(x1, x2, out) # x1 != x2

np.isnan(x, out)
np.isnat(x, out)

np.isfinite(x, out)

np.isinf(x, out)
np.isposinf(x)
np.isneginf(x)

np.isclose(a, b, rtol, equal_nan)
np.allclose(a, b, rtol, equal_nan)

np.array_equal(a1, a2, equal_nan)
np.array_equiv(a1, a2, equal_nan)
```

### Searching

```python
np.argmin(a, axis, out)
np.nanargmin(a, axis, out)

np.argmax(a, axis, out)
np.nanargmax(a, axis, out)

np.where(condition, x, y)
np.argwhere(condition)

np.nonzero(a)
np.flatnonzero(a)

np.searchsorted(a, v, side)
```

In [16]:
import numpy as np

In [21]:
np.where(np.arange(5) > 0)

(array([1, 2, 3, 4]),)

In [22]:
np.argwhere(np.arange(5) > 0)

array([[1],
       [2],
       [3],
       [4]])

In [24]:
arr = np.arange(5)
arr[np.argwhere(arr > 0)], arr[np.where(arr > 0)]

(array([[1],
        [2],
        [3],
        [4]]),
 array([1, 2, 3, 4]))

In [25]:
np.nonzero(arr)

(array([1, 2, 3, 4]),)

In [27]:
np.flatnonzero(arr)

array([1, 2, 3, 4])

In [29]:
arr = np.arange(20).reshape(4, 5)
np.flatnonzero(arr > 5)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
np.nonzero(arr > 5)

(array([1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [31]:
np.where(arr > 5)

(array([1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [32]:
np.argwhere(arr > 5)

array([[1, 1],
       [1, 2],
       [1, 3],
       [1, 4],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3],
       [3, 4]])